# -*- coding: utf-8 -*-
"""Competitors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eB3a1IFUBM6yEZkG3xj4_0KjlSkiaDbg

Здравствуйте, задача решена. Но есть пару недочетов, не хватило времени разобраться и решить корректно:

1.   При считывании файла пропадает 1 строка results = pd.read_csv("results_RUN.txt", sep = ' ', header = None, names = names), хотя заголовок отключила. Скорее всего есть какие-то еще параметры, отвечающие за это
2.   Финальное время забега не откорректировано до ожидаемого формата. Не нашла пока красивого варианта. Одно из решение - привести к строке, а из нее срезом взять необходимые символы

Путь к файлу можно изменить на подходящий, задание выполняла в google colab
"""

from google.colab import drive
drive.mount('/content/drive')

# модуль os предоставляет множество функций для работы с операционной системой
import os

# смена рабочей директории
os.chdir('drive/MyDrive/Sport')

import pandas as pd

competitors2 = pd.read_json('competitors2.json', orient = 'index', encoding='utf-8')
competitors2.reset_index(inplace= True)
competitors2['index'] = competitors2['index'].astype('str')
competitors2.head(5)

names = ['index', 'Start', 'Time']
results = pd.read_csv("results_RUN.txt", sep = ' ', header = None, names = names)
results['index'] = results['index'].astype('str')
results.head(5)

results.shape

start = results['Start'] == 'start'
finish = results['Start'] == 'finish'
results_sf = pd.merge(results[start], results[finish], on = 'index')
results_sf = results_sf.drop(columns = ['Start_x', 'Start_y'])
results_sf.head(5)

total_table = competitors2.merge(results_sf, how = 'left')
total_table.head(5)

total_table['Time_x'] = total_table['Time_x'].astype("datetime64[ns]")
total_table['Time_y'] = total_table['Time_y'].astype("datetime64[ns]")
total_table['Total time'] = total_table['Time_y'] - total_table['Time_x']
total_table = total_table.drop(['Time_x', 'Time_y'], axis = 1)
total_table = total_table.sort_values(by='Total time', ascending=True)
total_table.reset_index(drop=True, inplace=True)
total_table.head()

total_table['number'] = range(1, total_table.shape[0] + 1)

total_table

total_table = total_table[['number', 'index', 'Surname', 'Name', 'Total time']]
total_table = total_table.rename(columns = {'number' : 'Место', 'index' : 'Нагрудный номер', 'Surname' : 'Имя', 'Name' : 'Фамилия', 'Total time' : 'Результат'}) #, inplace = True)
total_table.head(5)

total_table.to_csv('Result.csv', index = False)